name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run ESLint
        working-directory: ./app
        run: npm run lint
